Add WIFISerialCommunication
LucidVR/lucidgloves-hardware pull request #106
Opened 2023-06-05 17:13 UTC by REXXER301

2023-06-05 17:21 UTC, REXXER301 commented
Fixed and tested, should work now

2023-06-05 18:20 UTC, danwillm requested changes
This is looking pretty good to me, thank you. Lucas will probably also need to do a pass before merging it, and I can find some time to work on adding WiFi to the driver.

2023-06-05 18:20 UTC, danwillm commented on firmware/lucidgloves-firmware/_main.ino
> +  WIFISerialCommunication
I don't think this needs to be here?
```suggestion
```

2023-06-05 18:20 UTC, danwillm commented on firmware/lucidgloves-firmware/AdvancedConfig.h
> +#define ECHO_WIRELESS_DATA false//Should the bluetooth or wifi data be echoed over serial for debugging
Is this actually used for bluetooth?

2023-06-05 18:20 UTC, danwillm commented on firmware/lucidgloves-firmware/WIFISerialCommunication.ino
> +    #endif
Should this now be `ECHO_WIRELESS_DATA`?

```suggestion
    #if ECHO_WIRELESS_DATA
    Serial.print(data);
    Serial.flush();
    #endif
```

2023-06-05 18:20 UTC, danwillm commented on firmware/lucidgloves-firmware/lucidgloves-firmware.ino
> +
✂️ newlines here, please

2023-06-10 00:10 UTC, danwillm requested changes
one small thing and then i think this will be ready to merge

2023-06-10 00:10 UTC, danwillm commented on firmware/lucidgloves-firmware/lucidgloves-firmware.ino
> +
Cut these two newlines out, please.

2023-11-12 18:38 UTC, jawaff commented
This is done right? The newlines have been removed as requested. Once this is merged we'll have wireless support for the faemod, so it's kind of a big deal.

2023-11-14 08:12 UTC, REXXER301 commented
> This is done right? The newlines have been removed as requested. Once this is merged we'll have wireless support for the faemod, so it's kind of a big deal.

Not entirely, you still need the [Server](https://github.com/REXXER301/TCP-COM-Reroute.git) to work, which needs some polishing. Adding this directly to the opengloves-driver shouldn't be too difficult and would remove the need for the virtual com ports, but I lack the time to do so.

If you want to use the wifi support with the fae mod today you can create 2 linked com ports with [com0com](https://com0com.sourceforge.net/) and use my [Reroute Server](https://github.com/REXXER301/TCP-COM-Reroute.git)

2024-12-12 13:57 UTC, AthemiS13 commented
@REXXER301 Does this work? If yes, how to get it running

2025-07-25 16:24 UTC, REXXER301 commented
> @REXXER301 Does this work? If yes, how to get it running

@danwillm could we merge this for the few people that stumble over this?
Even though the driver does not fully support it yet, the patch tape solution with [tcp to com reroute](https://github.com/REXXER301/TCP-COM-Reroute) does work and is not that difficult to set up. There even seems to be a [sophisticated solution](https://freecomportredirector.com/), didn't test it yet though.

2025-10-25 17:38 UTC, lucas-vrtech commented
Hey @REXXER301 !

I'm really sorry for the delay in getting this merged in, and thank you so much for continuing to support the project while I've been inactive. One of the blockers was that I needed to merge in the prototype 5 branch first, because it had some refactors to the .ino structure of the project, moving a lot of files to cpp's.

Once we get the merge conflict here resolved this will be good to go ahead and merge. I'm happy to help with resolving it as well, feel free to connect with me on Discord if preferred.

Thanks again.

2025-10-29 16:21 UTC, closed without merging