Median filtering, and analog value clamping
LucidVR/lucidgloves-hardware pull request #27
Opened 2021-10-03 06:40 UTC by edencomputing

I've added an optional median filter using the RunningMedian library (https://github.com/RobTillaart/RunningMedian), which can help filtering noisy sensors like bend/flex sensors or hall sensors.  Default disabled, and the library only needs to be installed if enabled.

I've also added clamps to the values produced by mapping the analogRead() output against the 0 .. ANALOG_MAX range, which helps when constant calibration is disabled to prevent under or overflow.  Defaults enabled.

Additionally I've added clamps to the possible flexion min and max values, which helps with my bend and hall sensor gloves which can occasionally produce spurious output that reach past the normal min/max values.  This lets you tune the possible range of calibration values and prevents the min/max used in the map from going out of control.  Defaults disabled.

Finally, I've replaced the math being done to calibrate across the 0 .. ANALOG_MAX range with the arduino map() function, for simplicity. I've verified that the values produced by the original equation and those produced by the map() function are identical, so this should not produce a functional change.

2021-10-05 10:22 UTC, danwillm approved these changes

2021-10-17 18:44 UTC, lucas-vrtech requested changes

2021-10-17 18:44 UTC, lucas-vrtech commented on firmware/lucidgloves-firmware/AdvancedConfig.h
> +#define ENABLE_MEDIAN_FILTER false //use the median of the previous values, helps reduce noise
Can you please specify here that you need to install the library in order to enable this setting?

2021-10-17 21:15 UTC, TwidgeVR commented on firmware/lucidgloves-firmware/AdvancedConfig.h
> +#define ENABLE_MEDIAN_FILTER false //use the median of the previous values, helps reduce noise
Good note, I've added a note to install the library and a link to it's docs

2021-10-17 21:17 UTC, lucas-vrtech commented
Great, thanks! Can you go ahead and merge LucidVR:main into your fork to resolve the merge conflicts?

2021-10-17 22:14 UTC, lucas-vrtech approved these changes

2021-10-17 22:15 UTC, merged