Add support for smoother force feedback by using writeMicroseconds.
LucidVR/lucidgloves-hardware pull request #55
Opened 2022-01-23 22:13 UTC by JohnRThomas

This will need to be supported in the driver as well to send large values that 0-180. The driver should send a value from 0-4096 to future proof this. Might as well have the firmware scale the value down to what it can support.

On EPS32 the servo library uses micro second pulses from 500-2500, on Arduino it uses 544-2400
https://github.com/jkb-git/ESP32Servo/blob/master/src/ESP32_Servo.h
https://github.com/arduino-libraries/Servo/blob/master/src/Servo.h

This gives us around 2000 steps instead of just the 181 that we get today.

Today we basically do: 
`map(map(hapticLimit, 0, 4096, 0, 180), 0, 180, MICRO_SECOND_MIN, MICRO_SECOND_MAX)`
we should be doing:
`map(hapticLimit, 0, 4096, MICRO_SECOND_MIN, MICRO_SECOND_MAX)`

2022-01-23 22:29 UTC, JohnRThomas commented
After talking to @danwillm, it looks like the driver already send 1-1000. This change then gives use 1001 steps of FFB resolution instead of just 181.

This could be scaled up in the future if we ever have a glove that supports better resolution just by tweaking the config file.

2022-01-25 22:03 UTC, JohnRThomas commented
Just noticed that `map` doesn't limit the output. We should use `constrain` instead of `map`.

2022-01-26 06:07 UTC, JohnRThomas commented
Servo output values are now constrained and the mapping is now performed as floating point numbers again.

2022-02-01 08:53 UTC, danwillm requested changes

2022-02-01 08:53 UTC, danwillm commented on firmware/lucidgloves-firmware/haptics.ino
>  }
does this need to return a `long`? Also I'd leave it up to the compiler to decide when to inline the function.

2022-04-25 05:10 UTC, closed without merging